# Stage: Development
FROM node:20.10.0
WORKDIR /app
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm install
COPY . .
RUN export VERSION=$(npm run version)
EXPOSE 3000
CMD ["npm", "start"]