export type MasterDuelCanvas = {
    previewCanvas: React.RefObject<HTMLCanvasElement>,
    drawCanvas: React.RefObject<HTMLCanvasElement>,
    frameCanvas: React.RefObject<HTMLCanvasElement>,
    artCanvas: React.RefObject<HTMLCanvasElement>,
    specialFrameCanvas: React.RefObject<HTMLCanvasElement>,
    subFamilyCanvas: React.RefObject<HTMLCanvasElement>,
    pendulumScaleCanvas: React.RefObject<HTMLCanvasElement>,
    pendulumEffectCanvas: React.RefObject<HTMLCanvasElement>,
    typeCanvas: React.RefObject<HTMLCanvasElement>,
    effectCanvas: React.RefObject<HTMLCanvasElement>,
    nameCanvas: React.RefObject<HTMLCanvasElement>,
    attributeCanvas: React.RefObject<HTMLCanvasElement>,
    statCanvas: React.RefObject<HTMLCanvasElement>,
    setIdCanvas: React.RefObject<HTMLCanvasElement>,
    passcodeCanvas: React.RefObject<HTMLCanvasElement>,
    creatorCanvas: React.RefObject<HTMLCanvasElement>,
    stickerCanvas: React.RefObject<HTMLCanvasElement>,
};