import { FontData } from './font-data-effect';

export type NameFontData = {
    value: string,
    labelKey: string,
    fontData: FontData,
};
export const NameFontDataMap: Record<'Default' | 'Arial' | 'OCG', NameFontData> = {
    Default: {
        value: 'Default',
        labelKey: 'input.name-style.font-type.default',
        fontData: {
            alphabetFont: 'MatrixRegularSmallCaps',
            font: 'MatrixRegularSmallCaps',
            furiganaFont: 'DFHSGothic-W3-WIN-RKSJ-H',
            ordinalFont: '"DFKakuTaiHiStd-W4"',
            fontStyle: 'tcg',
            symbolFont: 'matrix',
            symbolFontRatio: 0.775,
            headTextHeightRatio: 0.55,
            fontList: [{
                bulletSymbolWidth: 64,
                fontSize: 91.5,
                headTextFontRatio: 0.190,
                letterSpacing: 0.015,
                lineCount: 1,
                lineHeight: 91.5,
                offsetY: 0,
            }],
            letterDeviationMap: {
                i: { yOffset: 1, yRatio: 1.03 },
                ì: { yOffset: 1, yRatio: 1.03 },
                í: { yOffset: 1, yRatio: 1.03 },
                î: { yOffset: 1, yRatio: 1.03 },
                ï: { yOffset: 1, yRatio: 1.03 },
                ĩ: { yOffset: 1, yRatio: 1.03 },
                ī: { yOffset: 1, yRatio: 1.03 },
                ĭ: { yOffset: 1, yRatio: 1.03 },
                į: { yOffset: 1, yRatio: 1.03 },
                ǐ: { yOffset: 1, yRatio: 1.03 },
                ȉ: { yOffset: 1, yRatio: 1.03 },
                ȋ: { yOffset: 1, yRatio: 1.03 },
                ɨ: { yOffset: 1, yRatio: 1.03 },
                ɩ: { yOffset: 1, yRatio: 1.03 },
                ᵹ: { yOffset: 1, yRatio: 1.03 },
                ᵼ: { yOffset: 1, yRatio: 1.03 },
                ᶖ: { yOffset: 1, yRatio: 1.03 },
                ḭ: { yOffset: 1, yRatio: 1.03 },
                ḯ: { yOffset: 1, yRatio: 1.03 },
                ỉ: { yOffset: 1, yRatio: 1.03 },
                ị: { yOffset: 1, yRatio: 1.03 },
                I: { yOffset: 1, yRatio: 1.022 },
                Ì: { yOffset: 1, yRatio: 1.022 },
                Í: { yOffset: 1, yRatio: 1.022 },
                Î: { yOffset: 1, yRatio: 1.022 },
                Ï: { yOffset: 1, yRatio: 1.022 },
                Ĩ: { yOffset: 1, yRatio: 1.022 },
                Ī: { yOffset: 1, yRatio: 1.022 },
                Ĭ: { yOffset: 1, yRatio: 1.022 },
                Į: { yOffset: 1, yRatio: 1.022 },
                İ: { yOffset: 1, yRatio: 1.022 },
                Ɩ: { yOffset: 1, yRatio: 1.022 },
                Ɨ: { yOffset: 1, yRatio: 1.022 },
                Ǐ: { yOffset: 1, yRatio: 1.022 },
                Ȉ: { yOffset: 1, yRatio: 1.022 },
                Ȋ: { yOffset: 1, yRatio: 1.022 },
                Ḭ: { yOffset: 1, yRatio: 1.022 },
                Ḯ: { yOffset: 1, yRatio: 1.022 },
                Ỉ: { yOffset: 1, yRatio: 1.022 },
                Ị: { yOffset: 1, yRatio: 1.022 },
                E: { yOffset: 1, yRatio: 1.04 },
                Ĕ: { yOffset: 1, yRatio: 1.04 },
                ĕ: { yOffset: 1, yRatio: 1.04 },
                Ḝ: { yOffset: 1, yRatio: 1.04 },
                ḝ: { yOffset: 1, yRatio: 1.04 },
                Ȇ: { yOffset: 1, yRatio: 1.04 },
                ȇ: { yOffset: 1, yRatio: 1.04 },
                Ê: { yOffset: 1, yRatio: 1.04 },
                ê: { yOffset: 1, yRatio: 1.04 },
                Ê̄: { yOffset: 1, yRatio: 1.04 },
                ê̄: { yOffset: 1, yRatio: 1.04 },
                Ê̌: { yOffset: 1, yRatio: 1.04 },
                ê̌: { yOffset: 1, yRatio: 1.04 },
                Ề: { yOffset: 1, yRatio: 1.04 },
                ề: { yOffset: 1, yRatio: 1.04 },
                Ế: { yOffset: 1, yRatio: 1.04 },
                ế: { yOffset: 1, yRatio: 1.04 },
                Ể: { yOffset: 1, yRatio: 1.04 },
                ể: { yOffset: 1, yRatio: 1.04 },
                Ễ: { yOffset: 1, yRatio: 1.04 },
                ễ: { yOffset: 1, yRatio: 1.04 },
                Ệ: { yOffset: 1, yRatio: 1.04 },
                ệ: { yOffset: 1, yRatio: 1.04 },
                Ẻ: { yOffset: 1, yRatio: 1.04 },
                ẻ: { yOffset: 1, yRatio: 1.04 },
                Ḙ: { yOffset: 1, yRatio: 1.04 },
                ḙ: { yOffset: 1, yRatio: 1.04 },
                Ě: { yOffset: 1, yRatio: 1.04 },
                ě: { yOffset: 1, yRatio: 1.04 },
                Ɇ: { yOffset: 1, yRatio: 1.04 },
                ɇ: { yOffset: 1, yRatio: 1.04 },
                Ė: { yOffset: 1, yRatio: 1.04 },
                ė: { yOffset: 1, yRatio: 1.04 },
                Ė́: { yOffset: 1, yRatio: 1.04 },
                ė́: { yOffset: 1, yRatio: 1.04 },
                Ė̃: { yOffset: 1, yRatio: 1.04 },
                ė̃: { yOffset: 1, yRatio: 1.04 },
                Ẹ: { yOffset: 1, yRatio: 1.04 },
                ẹ: { yOffset: 1, yRatio: 1.04 },
                Ë: { yOffset: 1, yRatio: 1.04 },
                ë: { yOffset: 1, yRatio: 1.04 },
                È: { yOffset: 1, yRatio: 1.04 },
                è: { yOffset: 1, yRatio: 1.04 },
                È̩: { yOffset: 1, yRatio: 1.04 },
                è̩: { yOffset: 1, yRatio: 1.04 },
                Ȅ: { yOffset: 1, yRatio: 1.04 },
                ȅ: { yOffset: 1, yRatio: 1.04 },
                É: { yOffset: 1, yRatio: 1.04 },
                é: { yOffset: 1, yRatio: 1.04 },
                É̩: { yOffset: 1, yRatio: 1.04 },
                Ē: { yOffset: 1, yRatio: 1.04 },
                ē: { yOffset: 1, yRatio: 1.04 },
                Ḕ: { yOffset: 1, yRatio: 1.04 },
                ḕ: { yOffset: 1, yRatio: 1.04 },
                Ḗ: { yOffset: 1, yRatio: 1.04 },
                ḗ: { yOffset: 1, yRatio: 1.04 },
                Ẽ: { yOffset: 1, yRatio: 1.04 },
                ẽ: { yOffset: 1, yRatio: 1.04 },
                Ḛ: { yOffset: 1, yRatio: 1.04 },
                ḛ: { yOffset: 1, yRatio: 1.04 },
                Ę: { yOffset: 1, yRatio: 1.04 },
                ę: { yOffset: 1, yRatio: 1.04 },
                Ę́: { yOffset: 1, yRatio: 1.04 },
                ę́: { yOffset: 1, yRatio: 1.04 },
                Ę̃: { yOffset: 1, yRatio: 1.04 },
                ę̃: { yOffset: 1, yRatio: 1.04 },
                Ȩ: { yOffset: 1, yRatio: 1.04 },
                ȩ: { yOffset: 1, yRatio: 1.04 },
                E̩: { yOffset: 1, yRatio: 1.04 },
                e̩: { yOffset: 1, yRatio: 1.04 },
                ᶒ: { yOffset: 1, yRatio: 1.04 },
            },
        },
    },
    Arial: {
        value: 'Arial',
        labelKey: 'input.name-style.font-type.arial',
        fontData: {
            alphabetFont: 'Arial',
            font: 'Arial',
            furiganaFont: 'DFHSGothic-W3-WIN-RKSJ-H',
            ordinalFont: '"DFKakuTaiHiStd-W4"',
            fontStyle: 'tcg',
            symbolFont: 'matrix',
            symbolFontRatio: 0.775,
            headTextHeightRatio: 0.825,
            weight: 'bold',
            fontList: [{
                bulletSymbolWidth: 40.67,
                fontSize: 61,
                headTextFontRatio: 0.190,
                letterSpacing: -0.14,
                lineCount: 1,
                lineHeight: 61,
                offsetY: 3,
            }],
        },
    },
    OCG: {
        value: 'OCG',
        labelKey: 'input.name-style.font-type.ocg',
        fontData: {
            alphabetFont: '"Yu-Gi-Oh! DF Leisho 3"',
            font: '"Yu-Gi-Oh! DF Leisho 3"',
            furiganaFont: 'DFHSGothic-W3-WIN-RKSJ-H',
            headTextHeightRatio: 0.775,
            headTextOverflow: 'condense',
            headTextBold: true,
            metricMethod: 'name',
            numberFont: 'DFKakuTaiHiStd-W4',
            numberFontRatio: 1.00,
            ordinalFont: '"DFKakuTaiHiStd-W4"',
            symbolFont: 'matrix',
            symbolFontRatio: 0.775,
            fontStyle: 'ocg',
            fontList: [{
                bulletSymbolWidth: 42.67,
                fontSize: 64,
                headTextFontRatio: 0.175,
                headTextSpacing: 3,
                letterSpacing: -0.03,
                lineCount: 1,
                lineHeight: 64,
                offsetY: 0,
            }],
        }
    },
};