import { FontData } from './font-data-effect';

export type NameFontData = {
    value: string,
    labelKey: string,
    fontData: FontData,
};
export const NameFontDataMap: Record<'Default' | 'Arial' | 'OCG', NameFontData> = {
    Default: {
        value: 'Default',
        labelKey: 'input.name-style.font-type.default',
        fontData: {
            alphabetFont: 'MatrixRegularSmallCaps, Times New Roman',
            font: 'MatrixRegularSmallCaps, Times New Roman',
            fontStyle: 'tcg',
            furiganaFont: 'DFHSGothic-W3-WIN-RKSJ-H',
            headTextHeightRatio: 0.55,
            ordinalFont: '"DFKakuTaiHiStd-W4"',
            symbolFont: 'matrix, Times New Roman',
            symbolFontRatio: 0.775,
            vietnameseFont: 'MatrixRegularSmallCaps',
            vietnameseFontRatio: 1,
            variant: 'default-name',
            fontList: [{
                bulletWidth: 64,
                fontSize: 91,
                headTextFontRatio: 0.190,
                letterSpacing: 0.015,
                lineCount: 1,
                lineHeight: 91,
                offsetY: 0,
            }],
            letterOffsetMap: {
                '★': { ratio: 0.55, baseline: -0.05, yRatio: 1 },
                '☆': { ratio: 0.55, baseline: -0.05, yRatio: 1 },
                '¡': { ratio: 1, baseline: -0.098, edge: 0.02, yRatio: 0.58 },
            },
            letterDeviationMap: {
                '1': {
                    threshold: 0,
                    letterMap: {
                        I: { baseLetter: 'I' },
                        i: { baseLetter: 'i' },
                        //             Ì: { uniformBoxAscent: 1 },
                        //             Í: { uniformBoxAscent: 1 },
                        //             Î: { uniformBoxAscent: 1 },
                        //             Ï: { uniformBoxAscent: 1 },
                        //             ì: { uniformBoxAscent: 1 },
                        //             í: { uniformBoxAscent: 1 },
                        //             î: { uniformBoxAscent: 1 },
                        //             ï: { uniformBoxAscent: 1 },
                        //             Ĩ: { uniformBoxAscent: 1 },
                        //             ĩ: { uniformBoxAscent: 1 },
                        //             Ī: { uniformBoxAscent: 1 },
                        //             ī: { uniformBoxAscent: 1 },
                        //             Ỉ: { uniformBoxAscent: 1 },
                        //             ỉ: { uniformBoxAscent: 1 },
                        //             Ị: { uniformBoxAscent: 1 },
                        //             ị: { uniformBoxAscent: 1 },

                        E: { baseLetter: 'E' },
                        e: { baseLetter: 'e' },
                        //             È: { uniformBoxAscent: 1 },
                        //             É: { uniformBoxAscent: 1 },
                        //             Ê: { uniformBoxAscent: 1 },
                        //             Ê̄: { uniformBoxAscent: 1 },
                        //             Ê̌: { uniformBoxAscent: 1 },
                        //             Ë: { uniformBoxAscent: 1 },
                        //             è: { uniformBoxAscent: 1 },
                        //             é: { uniformBoxAscent: 1 },
                        //             ê: { uniformBoxAscent: 1 },
                        //             ê̄: { uniformBoxAscent: 1 },
                        //             ê̌: { uniformBoxAscent: 1 },
                        //             ë: { uniformBoxAscent: 1 },
                        //             Ē: { uniformBoxAscent: 1 },
                        //             ē: { uniformBoxAscent: 1 },
                        //             Ẻ: { uniformBoxAscent: 1 },
                        //             ẻ: { uniformBoxAscent: 1 },
                        //             Ẽ: { uniformBoxAscent: 1 },
                        //             ẽ: { uniformBoxAscent: 1 },
                        //             Ế: { uniformBoxAscent: 1 },
                        //             ế: { uniformBoxAscent: 1 },
                        //             Ề: { uniformBoxAscent: 1 },
                        //             ề: { uniformBoxAscent: 1 },
                        //             Ể: { uniformBoxAscent: 1 },
                        //             ể: { uniformBoxAscent: 1 },
                        //             Ễ: { uniformBoxAscent: 1 },
                        //             ễ: { uniformBoxAscent: 1 },
                        //             E̩: { uniformBoxAscent: 1 },
                        //             e̩: { uniformBoxAscent: 1 },
                        //             È̩: { uniformBoxAscent: 1 },
                        //             É̩: { uniformBoxAscent: 1 },
                        //             è̩: { uniformBoxAscent: 1 },
                        //             Ẹ: { uniformBoxAscent: 1 },
                        //             ẹ: { uniformBoxAscent: 1 },
                        //             Ệ: { uniformBoxAscent: 1 },
                        //             ệ: { uniformBoxAscent: 1 },

                        N: { baseLetter: 'N' },
                        n: { baseLetter: 'n' },
                    },
                },
                '2': {
                    threshold: 0,
                    letterMap: {
                        I: { baseLetter: 'I' },
                        i: { baseLetter: 'i' },
                        Ì: { baseLetter: 'I' },
                        Í: { baseLetter: 'I' },
                        Î: { baseLetter: 'I' },
                        Ï: { baseLetter: 'I' },
                        ì: { baseLetter: 'i' },
                        í: { baseLetter: 'i' },
                        î: { baseLetter: 'i' },
                        ï: { baseLetter: 'i' },
                        Ĩ: { baseLetter: 'I' },
                        ĩ: { baseLetter: 'i' },
                        Ī: { baseLetter: 'I' },
                        ī: { baseLetter: 'i' },
                        Ỉ: { baseLetter: 'I' },
                        ỉ: { baseLetter: 'i' },
                        Ị: { baseLetter: 'I' },
                        ị: { baseLetter: 'i' },

                        E: { baseLetter: 'E' },
                        e: { baseLetter: 'e' },
                        È: { baseLetter: 'E' },
                        É: { baseLetter: 'E' },
                        Ê: { baseLetter: 'E' },
                        Ê̄: { baseLetter: 'E' },
                        Ê̌: { baseLetter: 'E' },
                        Ë: { baseLetter: 'E' },
                        è: { baseLetter: 'e' },
                        é: { baseLetter: 'e' },
                        ê: { baseLetter: 'e' },
                        ê̄: { baseLetter: 'e' },
                        ê̌: { baseLetter: 'e' },
                        ë: { baseLetter: 'e' },
                        Ē: { baseLetter: 'E' },
                        ē: { baseLetter: 'e' },
                        Ẻ: { baseLetter: 'E' },
                        ẻ: { baseLetter: 'e' },
                        Ẽ: { baseLetter: 'E' },
                        ẽ: { baseLetter: 'e' },
                        Ế: { baseLetter: 'E' },
                        ế: { baseLetter: 'e' },
                        Ề: { baseLetter: 'E' },
                        ề: { baseLetter: 'e' },
                        Ể: { baseLetter: 'E' },
                        ể: { baseLetter: 'e' },
                        Ễ: { baseLetter: 'E' },
                        ễ: { baseLetter: 'e' },
                        E̩: { baseLetter: 'E' },
                        e̩: { baseLetter: 'e' },
                        È̩: { baseLetter: 'E' },
                        É̩: { baseLetter: 'E' },
                        è̩: { baseLetter: 'e' },
                        Ẹ: { baseLetter: 'E' },
                        ẹ: { baseLetter: 'e' },
                        Ệ: { baseLetter: 'E' },
                        ệ: { baseLetter: 'e' },

                        N: { baseLetter: 'N' },
                        n: { baseLetter: 'n' },
                    },
                },
            },
        },
    },
    Arial: {
        value: 'Arial',
        labelKey: 'input.name-style.font-type.arial',
        fontData: {
            alphabetFont: 'Arial',
            font: 'Arial',
            fontStyle: 'tcg',
            furiganaFont: 'DFHSGothic-W3-WIN-RKSJ-H',
            headTextHeightRatio: 0.825,
            ordinalFont: '"DFKakuTaiHiStd-W4"',
            symbolFont: 'matrix',
            symbolFontRatio: 0.775,
            vietnameseFont: 'Arial',
            vietnameseFontRatio: 1,
            weight: 'bold',
            variant: 'arial-name',
            fontList: [{
                bulletWidth: 40.67,
                fontSize: 61,
                headTextFontRatio: 0.190,
                letterSpacing: -0.14,
                lineCount: 1,
                lineHeight: 61,
                offsetY: 3,
            }],
        },
    },
    OCG: {
        value: 'OCG',
        labelKey: 'input.name-style.font-type.ocg',
        fontData: {
            alphabetFont: '"Yu-Gi-Oh! DF Leisho 3"',
            font: '"Yu-Gi-Oh! DF Leisho 3"',
            fontStyle: 'ocg',
            furiganaFont: 'DFHSGothic-W3-WIN-RKSJ-H',
            headTextBold: true,
            headTextHeightRatio: 0.775,
            headTextOverflow: 'condense',
            metricMethod: 'name',
            numberFont: 'DFKakuTaiHiStd-W4',
            numberFontRatio: 1.00,
            ordinalFont: '"DFKakuTaiHiStd-W4"',
            symbolFont: 'matrix',
            symbolFontRatio: 0.775,
            vietnameseFont: '"Yu-Gi-Oh! DF Leisho 3"',
            vietnameseFontRatio: 1,
            variant: 'ocg-name',
            fontList: [{
                bulletWidth: 42.67,
                fontSize: 64,
                headTextFontRatio: 0.175,
                headTextSpacing: 3,
                letterSpacing: -0.03,
                lineCount: 1,
                lineHeight: 64,
                offsetY: 0,
            }],
        }
    },
};