import { FontData } from './font-data-effect';

export type NameFontData = {
    value: string,
    labelKey: string,
    fontData: FontData,
};
export const NameFontDataMap: Record<'Default' | 'Arial' | 'OCG', NameFontData> = {
    Default: {
        value: 'Default',
        labelKey: 'input.name-style.font-type.default',
        fontData: {
            alphabetFont: 'MatrixRegularSmallCaps',
            font: 'MatrixRegularSmallCaps',
            furiganaFont: 'DFHSGothic-W3-WIN-RKSJ-H',
            ordinalFont: '"DFKakuTaiHiStd-W4"',
            fontStyle: 'tcg',
            symbolFont: 'matrix',
            symbolFontRatio: 0.775,
            headTextHeightRatio: 0.55,
            fontList: [{
                bulletSymbolWidth: 64,
                fontSize: 91.5,
                headTextFontRatio: 0.190,
                letterSpacing: 0.015,
                lineCount: 1,
                lineHeight: 91.5,
                offsetY: 0,
            }],
            letterDeviationMap: {
                '1': {
                    threshold: 0.94,
                    letterMap: {
                        I: { uniformBoxDescent: 1 },
                        i: { uniformBoxDescent: 1 },
                        Ì: { uniformBoxDescent: 1 },
                        Í: { uniformBoxDescent: 1 },
                        Î: { uniformBoxDescent: 1 },
                        Ï: { uniformBoxDescent: 1 },
                        ì: { uniformBoxDescent: 1 },
                        í: { uniformBoxDescent: 1 },
                        î: { uniformBoxDescent: 1 },
                        ï: { uniformBoxDescent: 1 },
                        Ĩ: { uniformBoxDescent: 1 },
                        ĩ: { uniformBoxDescent: 1 },
                        Ī: { uniformBoxDescent: 1 },
                        ī: { uniformBoxDescent: 1 },
                        Ỉ: { uniformBoxDescent: 1 },
                        ỉ: { uniformBoxDescent: 1 },
                        Ị: { uniformBoxDescent: 11 },
                        ị: { uniformBoxDescent: 11 },
        
                        E: { uniformBoxDescent: 1 },
                        È: { uniformBoxDescent: 1 },
                        É: { uniformBoxDescent: 1 },
                        Ê: { uniformBoxDescent: 1 },
                        Ê̄: { uniformBoxDescent: 1 },
                        Ê̌: { uniformBoxDescent: 1 },
                        Ë: { uniformBoxDescent: 1 },
                        è: { uniformBoxDescent: 1 },
                        é: { uniformBoxDescent: 1 },
                        ê: { uniformBoxDescent: 1 },
                        ê̄: { uniformBoxDescent: 1 },
                        ê̌: { uniformBoxDescent: 1 },
                        ë: { uniformBoxDescent: 1 },
                        Ē: { uniformBoxDescent: 1 },
                        ē: { uniformBoxDescent: 1 },
                        Ẻ: { uniformBoxDescent: 1 },
                        ẻ: { uniformBoxDescent: 1 },
                        Ẽ: { uniformBoxDescent: 1 },
                        ẽ: { uniformBoxDescent: 1 },
                        Ế: { uniformBoxDescent: 1 },
                        ế: { uniformBoxDescent: 1 },
                        Ề: { uniformBoxDescent: 1 },
                        ề: { uniformBoxDescent: 1 },
                        Ể: { uniformBoxDescent: 1 },
                        ể: { uniformBoxDescent: 1 },
                        Ễ: { uniformBoxDescent: 1 },
                        ễ: { uniformBoxDescent: 1 },
                        E̩: { uniformBoxDescent: 11 },
                        e̩: { uniformBoxDescent: 11 },
                        È̩: { uniformBoxDescent: 11 },
                        É̩: { uniformBoxDescent: 11 },
                        è̩: { uniformBoxDescent: 11 },
                        Ẹ: { uniformBoxDescent: 11 },
                        ẹ: { uniformBoxDescent: 11 },
                        Ệ: { uniformBoxDescent: 11 },
                        ệ: { uniformBoxDescent: 11 },
                    },
                },
                '2': {
                    threshold: 0,
                    letterMap: {
                        I: { uniformBoxDescent: 1 },
                        i: { uniformBoxDescent: 1 },
                        Ì: { uniformBoxDescent: 1 },
                        Í: { uniformBoxDescent: 1 },
                        Î: { uniformBoxDescent: 1 },
                        Ï: { uniformBoxDescent: 1 },
                        ì: { uniformBoxDescent: 1 },
                        í: { uniformBoxDescent: 1 },
                        î: { uniformBoxDescent: 1 },
                        ï: { uniformBoxDescent: 1 },
                        Ĩ: { uniformBoxDescent: 1 },
                        ĩ: { uniformBoxDescent: 1 },
                        Ī: { uniformBoxDescent: 1 },
                        ī: { uniformBoxDescent: 1 },
                        Ỉ: { uniformBoxDescent: 1 },
                        ỉ: { uniformBoxDescent: 1 },
                        Ị: { uniformBoxDescent: 20 },
                        ị: { uniformBoxDescent: 20 },
        
                        E: { uniformBoxDescent: 1 },
                        È: { uniformBoxDescent: 1 },
                        É: { uniformBoxDescent: 1 },
                        Ê: { uniformBoxDescent: 1 },
                        Ê̄: { uniformBoxDescent: 1 },
                        Ê̌: { uniformBoxDescent: 1 },
                        Ë: { uniformBoxDescent: 1 },
                        è: { uniformBoxDescent: 1 },
                        é: { uniformBoxDescent: 1 },
                        ê: { uniformBoxDescent: 1 },
                        ê̄: { uniformBoxDescent: 1 },
                        ê̌: { uniformBoxDescent: 1 },
                        ë: { uniformBoxDescent: 1 },
                        Ē: { uniformBoxDescent: 1 },
                        ē: { uniformBoxDescent: 1 },
                        Ẻ: { uniformBoxDescent: 1 },
                        ẻ: { uniformBoxDescent: 1 },
                        Ẽ: { uniformBoxDescent: 1 },
                        ẽ: { uniformBoxDescent: 1 },
                        Ế: { uniformBoxDescent: 1 },
                        ế: { uniformBoxDescent: 1 },
                        Ề: { uniformBoxDescent: 1 },
                        ề: { uniformBoxDescent: 1 },
                        Ể: { uniformBoxDescent: 1 },
                        ể: { uniformBoxDescent: 1 },
                        Ễ: { uniformBoxDescent: 1 },
                        ễ: { uniformBoxDescent: 1 },
                        E̩: { uniformBoxDescent: 20 },
                        e̩: { uniformBoxDescent: 20 },
                        È̩: { uniformBoxDescent: 20 },
                        É̩: { uniformBoxDescent: 20 },
                        è̩: { uniformBoxDescent: 20 },
                        Ẹ: { uniformBoxDescent: 20 },
                        ẹ: { uniformBoxDescent: 20 },
                        Ệ: { uniformBoxDescent: 20 },
                        ệ: { uniformBoxDescent: 20 },
                    },
                },
            },
        },
    },
    Arial: {
        value: 'Arial',
        labelKey: 'input.name-style.font-type.arial',
        fontData: {
            alphabetFont: 'Arial',
            font: 'Arial',
            furiganaFont: 'DFHSGothic-W3-WIN-RKSJ-H',
            ordinalFont: '"DFKakuTaiHiStd-W4"',
            fontStyle: 'tcg',
            symbolFont: 'matrix',
            symbolFontRatio: 0.775,
            headTextHeightRatio: 0.825,
            weight: 'bold',
            fontList: [{
                bulletSymbolWidth: 40.67,
                fontSize: 61,
                headTextFontRatio: 0.190,
                letterSpacing: -0.14,
                lineCount: 1,
                lineHeight: 61,
                offsetY: 3,
            }],
        },
    },
    OCG: {
        value: 'OCG',
        labelKey: 'input.name-style.font-type.ocg',
        fontData: {
            alphabetFont: '"Yu-Gi-Oh! DF Leisho 3"',
            font: '"Yu-Gi-Oh! DF Leisho 3"',
            furiganaFont: 'DFHSGothic-W3-WIN-RKSJ-H',
            headTextHeightRatio: 0.775,
            headTextOverflow: 'condense',
            headTextBold: true,
            metricMethod: 'name',
            numberFont: 'DFKakuTaiHiStd-W4',
            numberFontRatio: 1.00,
            ordinalFont: '"DFKakuTaiHiStd-W4"',
            symbolFont: 'matrix',
            symbolFontRatio: 0.775,
            fontStyle: 'ocg',
            fontList: [{
                bulletSymbolWidth: 42.67,
                fontSize: 64,
                headTextFontRatio: 0.175,
                headTextSpacing: 3,
                letterSpacing: -0.03,
                lineCount: 1,
                lineHeight: 64,
                offsetY: 0,
            }],
        }
    },
};