/** Một số ký tự OCG sử dụng dạng halfwidth thay vì dạng fullwidth phổ thông và ngược lại, ta cần chủ động map lại. */
export const tcgToOCGLetterMap: Record<string, string> = {
    '０': '0',
    '１': '1',
    '２': '2',
    '３': '3',
    '４': '4',
    '５': '5',
    '６': '6',
    '７': '7',
    '８': '8',
    '９': '9',
    'ａ': 'a',
    'ｂ': 'b',
    'ｃ': 'c',
    'ｄ': 'd',
    'ｅ': 'e',
    'ｆ': 'f',
    'ｇ': 'g',
    'ｈ': 'h',
    'ｉ': 'i',
    'ｊ': 'j',
    'ｋ': 'k',
    'ｌ': 'l',
    'ｍ': 'm',
    'ｎ': 'n',
    'ｏ': 'o',
    'ｐ': 'p',
    'ｑ': 'q',
    'ｒ': 'r',
    'ｓ': 's',
    'ｔ': 't',
    'ｕ': 'u',
    'ｖ': 'v',
    'ｗ': 'w',
    'ｘ': 'x',
    'ｙ': 'y',
    'ｚ': 'z',
    'Ａ': 'A',
    'Ｂ': 'B',
    'Ｃ': 'C',
    'Ｄ': 'D',
    'Ｅ': 'E',
    'Ｆ': 'F',
    'Ｇ': 'G',
    'Ｈ': 'H',
    'Ｉ': 'I',
    'Ｊ': 'J',
    'Ｋ': 'K',
    'Ｌ': 'L',
    'Ｍ': 'M',
    'Ｎ': 'N',
    'Ｏ': 'O',
    'Ｐ': 'P',
    'Ｑ': 'Q',
    'Ｒ': 'R',
    'Ｓ': 'S',
    'Ｔ': 'T',
    'Ｕ': 'U',
    'Ｖ': 'V',
    'Ｗ': 'W',
    'Ｘ': 'X',
    'Ｙ': 'Y',
    'Ｚ': 'Z',
    '「': '｢',
    '」': '｣',
    '、': '､',
    '/': '／',
    ':': '：',
    // 'ー': 'ｰ',
    // '・': '･',
    // '・': '･',
    // '：': ':',
    'ꓯ': 'Ɐ',
    'ꓛ': 'Ɔ',
    'ꓱ': 'Ǝ',
    'ꓞ': 'Ⅎ',
    'ꓨ': '⅁',
    'ꓘ': 'Ʞ',
    'ꓶ': 'Ꞁ',
    '⅂': 'Ꞁ',
    'ꓒ': 'Ԁ',
    'ꓕ': 'Ʇ',
    'Ո': 'ꓵ',
    'ꓥ': 'Ʌ',
};
export const ocgToTCGLetterMap: Record<string, string> = {
    '０': '0',
    '１': '1',
    '２': '2',
    '３': '3',
    '４': '4',
    '５': '5',
    '６': '6',
    '７': '7',
    '８': '8',
    '９': '9',
    'ａ': 'a',
    'ｂ': 'b',
    'ｃ': 'c',
    'ｄ': 'd',
    'ｅ': 'e',
    'ｆ': 'f',
    'ｇ': 'g',
    'ｈ': 'h',
    'ｉ': 'i',
    'ｊ': 'j',
    'ｋ': 'k',
    'ｌ': 'l',
    'ｍ': 'm',
    'ｎ': 'n',
    'ｏ': 'o',
    'ｐ': 'p',
    'ｑ': 'q',
    'ｒ': 'r',
    'ｓ': 's',
    'ｔ': 't',
    'ｕ': 'u',
    'ｖ': 'v',
    'ｗ': 'w',
    'ｘ': 'x',
    'ｙ': 'y',
    'ｚ': 'z',
    'Ａ': 'A',
    'Ｂ': 'B',
    'Ｃ': 'C',
    'Ｄ': 'D',
    'Ｅ': 'E',
    'Ｆ': 'F',
    'Ｇ': 'G',
    'Ｈ': 'H',
    'Ｉ': 'I',
    'Ｊ': 'J',
    'Ｋ': 'K',
    'Ｌ': 'L',
    'Ｍ': 'M',
    'Ｎ': 'N',
    'Ｏ': 'O',
    'Ｐ': 'P',
    'Ｑ': 'Q',
    'Ｒ': 'R',
    'Ｓ': 'S',
    'Ｔ': 'T',
    'Ｕ': 'U',
    'Ｖ': 'V',
    'Ｗ': 'W',
    'Ｘ': 'X',
    'Ｙ': 'Y',
    'Ｚ': 'Z',
    // '｡': '。',
    '｢': '「',
    '｣': '」',
    '､': '、',
    '／': '/',
    '：': ':',
    // 'ｰ': 'ー',
    // '･': '・',
    // '･': '・',
    // ':': '：',
    'ꓯ': 'Ɐ',
    'ꓛ': 'Ɔ',
    'ꓱ': 'Ǝ',
    'ꓞ': 'Ⅎ',
    'ꓨ': '⅁',
    'ꓘ': 'Ʞ',
    'ꓶ': 'Ꞁ',
    '⅂': 'Ꞁ',
    'ꓒ': 'Ԁ',
    'ꓕ': 'Ʇ',
    'Ո': 'ꓵ',
    'ꓥ': 'Ʌ',
};

export const ocgToTCGTermMap: Record<string, string> = {
    /** monster type */
    '水': 'Aqua',
    '獣': 'Beast',
    '獣戦士': 'Beast-Warrior',
    '創造神': 'Creator God',
    'サイバース': 'Cyberse',
    '恐竜': 'Dinosaur',
    '幻神獣': 'Divine-Beast',
    'ドラゴン': 'Dragon',
    '天使': 'Fairy',
    '悪魔': 'Fiend',
    '魚': 'Fish',
    'ギャラクシー': 'Galaxy',
    '幻想魔': 'Illusion',
    '昆虫': 'Insect',
    '機械': 'Machine',
    '植物': 'Plant',
    'サイキック': 'Psychic',
    '炎': 'Pyro',
    '爬虫類': 'Reptile',
    '岩石': 'Rock',
    '海竜': 'Sea Serpent',
    '魔法使': 'Spellcaster',
    '雷': 'Thunder',
    '戦士': 'Warrior',
    '鳥獣': 'Winged Beast',
    '幻竜': 'Wyrm',
    'アンデット': 'Zombie',
    'サイボーグ': 'Cyborg',
    '天界戦士': 'Celestial Warrior',
    'ハイドラゴン': 'High Dragon',
    '魔導騎士': 'Magical Knight',
    'オメガサイキック': 'Omega Psychic',
    /** type */
    'モンスター': 'Monster',
    '魔法カード': 'Spell Card',
    '罠カード': 'Trap Card',
    'アクション': 'Action',
    /** subType */
    '通常': 'Normal',
    '効果': 'Effect',
    '儀式': 'Ritual',
    'フュージョン': 'Fusion', // Nằm trên vì có độ ưu tiên thấp hơn
    '融合': 'Fusion',
    'シンクロ': 'Synchro',
    'エクシーズ': 'Xyz',
    'ペンデュラム': 'Pendulum',
    'リンク': 'Link',
    'マキシマム': 'Maximum',
    'トークン': 'Token',
    /** ability */
    'チューナー': 'Tuner',
    'デュアル': 'Gemini',
    'リバース': 'Flip',
    'トゥーン': 'Toon',
    'スピリット': 'Spirit',
    'ユニオン': 'Union',
    /** creator */
    '©高橋和希 スタジオ・ダイス／集英社': '©1996 KAZUKI TAKAHASHI',
    '©スタジオ・ダイス／集英社・テレビ東京・KONAMI': '©2020 Studio Dice/SHUEISHA, TV TOKYO, KONAMI',
};
export const tcgToOCGTermMap = Object.entries(ocgToTCGTermMap).reduce((acc, cur) => {
    const [ocgTerm, tcgTerm] = cur;
    acc[tcgTerm] = ocgTerm;

    return acc;
}, {} as Record<string, string>);