export type FrameInfo = {
    name: string,
    edition: 'normal' | 'extendend',
    labelColor: string,
    labelBackgroundColor?: string,
    labelBackgroundColorList?: string[],
    labelBackgroundImage?: string,
};
export const FrameInfoMap: Record<string, FrameInfo> = {
    'normal': {
        name: 'normal',
        labelColor: '#ffffff',
        edition: 'normal',
        labelBackgroundColor: '#c49c5e',
    },
    'effect': {
        name: 'effect',
        labelColor: '#ffffff',
        edition: 'normal',
        labelBackgroundColor: '#b96c49',
    },
    'fusion': {
        name: 'fusion',
        labelColor: '#ffffff',
        edition: 'normal',
        labelBackgroundColor: '#8948a4',
    },
    'synchro': {
        name: 'synchro',
        labelColor: '#000',
        edition: 'normal',
        labelBackgroundColor: '#efefef',
    },
    'xyz': {
        name: 'xyz',
        labelColor: '#ffffff',
        edition: 'normal',
        labelBackgroundColor: '#000000',
    },
    'link': {
        name: 'link',
        labelColor: '#ffffff',
        edition: 'normal',
        labelBackgroundColor: '#0c8ac6',
    },
    'ritual': {
        name: 'ritual',
        labelColor: '#ffffff',
        edition: 'normal',
        labelBackgroundColor: '#5e85c9',
    },
    'spell': {
        name: 'spell',
        labelColor: '#ffffff',
        edition: 'normal',
        labelBackgroundColor: '#1b8f83',
    },
    'trap': {
        name: 'trap',
        labelColor: '#ffffff',
        edition: 'normal',
        labelBackgroundColor: '#c32a8c',
    },
    'token': {
        name: 'token',
        labelColor: '#ffffff',
        edition: 'normal',
        labelBackgroundColor: '#6f6c6b',
    },
    'dark-synchro': {
        name: 'dark-synchro',
        labelColor: '#ffffff',
        edition: 'extendend',
        labelBackgroundColor: '#4d4543',
    },
    'obelisk': {
        name: 'obelisk',
        labelColor: '#ffffff',
        edition: 'extendend',
        labelBackgroundColor: '#515eb0',
    },
    'osiris': {
        name: 'osiris',
        labelColor: '#ffffff',
        edition: 'extendend',
        labelBackgroundColor: '#bd5044',
    },
    'ra': {
        name: 'ra',
        labelColor: '#000',
        edition: 'extendend',
        labelBackgroundColor: '#b9ad34',
    },
    'raviel': {
        name: 'raviel',
        labelColor: '#ffffff',
        edition: 'extendend',
        labelBackgroundColor: '#313c5f',
    },
    'uria': {
        name: 'uria',
        labelColor: '#ffffff',
        edition: 'extendend',
        labelBackgroundColor: '#623320',
    },
    'hamon': {
        name: 'hamon',
        labelColor: '#ffffff',
        edition: 'extendend',
        labelBackgroundColor: '#534a19',
    },
    'lg-dragon': {
        name: 'lg-dragon',
        labelColor: '#ffffff',
        edition: 'extendend',
        labelBackgroundColor: '#4e84a4',
    },
    'speed-skill': {
        name: 'speed-skill',
        labelColor: '#ffffff',
        edition: 'extendend',
        labelBackgroundColor: '#199cd5',
    },
    'zarc': {
        name: 'zarc',
        labelColor: '#000',
        edition: 'extendend',
        labelBackgroundColorList: [
            'rgba(185,108,73,1)',
            'rgba(137,72,164,1)',
            'rgba(239,239,239,1)',
            'rgba(0,0,0,1)',
        ],
        labelBackgroundImage: `linear-gradient(90deg, ${[
            'rgba(185,108,73,1) 23%',
            'rgba(137,72,164,1) 27%',
            'rgba(137,72,164,1) 48%',
            'rgba(239,239,239,1) 52%',
            'rgba(239,239,239,1) 73%',
            'rgba(0,0,0,1) 77%',
        ].join(', ')})`,
    },
};
export const frameList = Object.values(FrameInfoMap);