import { Card } from 'src/model';


export const cardListToMse = (cardList: Card[]) => {
    const imageList: { blob: Blob, name: string }[] = [];
    const stringifiedCardList: string[][] = [[
        'has_styling: false',
        'notes: ',
        'time_created: 2020-12-19 12:07:03',
        'time_modified: 2026-06-14 11:26:51',
        'extra_data:',
        '	yugioh-series10:',
        '		mse_version: 2.0.1',
        'card_type: "pendulum synchro monster"',
        'name: "Balogar, Blinded by Fate"',
        'attribute: "light"',
        'level: "<sym-auto>*</sym-auto><sym-auto>*</sym-auto><sym-auto>*</sym-auto><sym-auto>*</sym-auto><sym-auto>*</sym-auto><sym-auto>*</sym-auto><sym-auto>*</sym-auto><sym-auto>*</sym-auto><sym-auto>*</sym-auto><sym-auto>*</sym-auto>"',
        'image: local_image_file("image1")',
        'type_1: "<word-list-monster>Psychic</word-list-monster>"',
        'type_2: "<word-list-card>Effect</word-list-card>"',
        'type_3: "<word-list-card></word-list-card>"',
        'type_4: "<word-list-card></word-list-card>"',
        'type_5: "<word-list-card></word-list-card>"',
        'monster_type: "<prefix>[</prefix><word-list-monster>Psychic</word-list-monster><sep><test>/</test></sep><word-list-card>Effect</word-list-card><sep-soft></sep-soft><word-list-card></word-list-card><sep-soft></sep-soft><word-list-card></word-list-card><sep>]<soft></soft></sep><word-list-card></word-list-card>"',
        'rule_text: "If your opponent have more cards in their GY than you do, you can Special Summon this card from your hand. Cannot be destroyed by Spell/Trap effects. While your opponent have more cards in their GY than you do, monsters they control lose ATK/DEF equal to the difference x 200 during your turn only. Monsters with 0 ATK cannot activate their effects, also their effects on the field are negated."',
        'attack: "2000"',
        'defense: "2000"',
        'blue_scale: "4"',
        'red_scale: "3"',
        'pendulum_text: "Balogar"',
        'gamecode: "01"',
        'rarity: "ultra rare"',
    ]];
    const resultList = [
        'mse_version: 2.0.1',
        'game: yugioh',
        'stylesheet: series10',
        'set_info:',
        '	title: "Path of Blind Gods"',
        '	gods_have_effects: false',
        'styling:',
        '	yugioh-series10:',
        '		mse_version: 2.0.1',
        '		language: "english"',
        '		template_style: "proxy-like"',
        '		name_color_override: false',
        '		name_color: rgb(254,254,254)',
        '		shadow_override: false',
        '		shadow_color: rgb(1,1,1)',
        '		copyright_color_override: false',
        '		copyright_color: rgb(254,254,254)',
        '		foil_texture: true',
        '		foil_texture_override: false',
        '		custom_foil: "defaultfoil"',
        '		image_frame: false',
        '		extended_artwork: "no"',
        '		lorebox_watermark: false',
        '		custom_watermark: "speedduel"',
        '		rules_alignment: "justified"',
        '		bold_effect_text: false',
        '		large_type: false',
        '		text_size: "small"',
        '		max_line_space: false',
        '		disable_hologram: false',
        '		pendulum_transparency: "true"',
        '		pendulum_size: "default"',
        '		pendulum_text_centering: false',
        '		is_ZARC_card: false',
        '		is_link_card: false',
        stringifiedCardList.map(entry => 'card:\n' + entry.map(entry => '	' + entry).join('\n')).join('\n'),
        'version_control:',
        '	type: none',
        'apprentice_code: ',
    ];

    console.log('🚀 ~ cardListToMse ~ resultList.join(\'\n\'):', resultList.join('\n'));
    return {
        error: null,
        set: new Blob([resultList.join('\n')], { type: 'text/plain' }),
        imageList,
    };
};